### ISSUE TITLE
Enhancement: using @anon with Task()?

### ISSUE THREAD

**Issue by sbromberger** [timholy/FastAnonymous.jl#11]
```
julia> using FastAnonymous

julia> Task(() -> 6)
Task (runnable) @0x0000000113a56cb0

julia> Task(@anon(() -> 8))
ERROR: TypeError: call: in typeassert, expected Function, got FastAnonymous.Fun{Ptr{Void} @0x000000011065d2b0,0xc22def3c77661774,()}
 in call at /usr/local/julia-latest/lib/julia/sys.dylib
```

Any way to use FastAnonymous with `Task()`?

**Comment by malmaud** [comment]
This will require a change to Julia - I've submitted a PR that fixes it. Fairt warning though, the overhead of `Task` is so large that I'm not sure you'll see any performance benefits to using `@anon` in this situation.

**Comment by malmaud** [comment]
Alright, this is fixed now on the latest Julia master.

**Comment by timholy** [comment]
Thanks, @malmaud!

**Comment by malmaud** [comment]
Glad to help.

**Comment by sbromberger** [comment]
Yup - this is awesome. Thank you.
