### ISSUE TITLE
Problem using FastAnonymous.jl in Julia 0.5

### ISSUE THREAD

**Issue by jmarcellopereira** [timholy/FastAnonymous.jl#17]

**Comment by timholy** [comment]
For anyone who stumbles across this, it's worth pointing out that anonymous function are already fast in julia 0.5. (FA inspired/provoked the solution in base julia.)

**Comment by dpo** [comment]
That would be worth indicating towards the top of the README.

**Comment by timholy** [comment]
@tkelman, can we retroactively deprecate this package on 0.5 and higher or can we only do it for 0.7?

**Comment by tkelman** [comment]
That would not be a good idea, it would suddenly make anything that depends on it not installable on 0.6.

**Comment by timholy** [comment]
That's what I thought. I'll make it uninstallable on 0.7.
