### ISSUE TITLE
[PkgEval] FastAnonymous may have a testing issue on Julia 0.4 (2015-02-09)

### ISSUE THREAD

**Issue by IainNZ** [timholy/FastAnonymous.jl#5]
[PackageEvaluator.jl](https://github.com/IainNZ/PackageEvaluator.jl) is a script that runs nightly. It attempts to load all Julia packages and run their tests (if available) on both the stable version of Julia (0.3) and the nightly build of the unstable version (0.4). The results of this script are used to generate a [package listing](http://pkg.julialang.org/) enhanced with testing results.

#### On Julia 0.4
* On **2015-02-07** the testing status was `Tests fail, but package loads.`
* On **2015-02-09** the testing status changed to `Package doesn't load.`

`Tests fail, but package loads.` means that PackageEvaluator found the tests for your package, executed them, and they didn't pass. However, trying to load your package with `using` worked.

`Package doesn't load.` means that PackageEvaluator did not find tests for your package. Additionally, trying to load your package with `using` failed.

*This issue was filed because your testing status became worse. No additional issues will be filed if your package remains in this state, and no issue will be filed if it improves. If you'd like to opt-out of these status-change messages, reply to this message saying you'd like to and @IainNZ will add an exception. If you'd like to discuss [PackageEvaluator.jl](https://github.com/IainNZ/PackageEvaluator.jl) please file an issue at the repository. For example, your package may be untestable on the test machine due to a dependency - an exception can be added.*

*Test log*:
```
>>> 'Pkg.add("FastAnonymous")' log
INFO: Installing FastAnonymous v0.0.1
INFO: Package database updated

>>> 'using FastAnonymous' log
Julia Version 0.4.0-dev+3225
Commit 6558327 (2015-02-09 04:52 UTC)
Platform Info:
  System: Linux (x86_64-unknown-linux-gnu)
  CPU: Intel(R) Xeon(R) CPU E5-2650 0 @ 2.00GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Sandybridge)
  LAPACK: libopenblas
  LIBM: libopenlibm
  LLVM: libLLVM-3.3

ERROR: LoadError: LoadError: UndefVarError: @ngenerate not defined
 in include at ./boot.jl:249
 in include_from_node1 at ./loading.jl:128
 in reload_path at ./loading.jl:152
 in _require at ./loading.jl:67
 in require at ./loading.jl:52
 in include at ./boot.jl:249
 in include_from_node1 at loading.jl:128
 in process_options at ./client.jl:319
 in _start at ./client.jl:403
while loading /home/idunning/pkgtest/.julia/v0.4/FastAnonymous/src/FastAnonymous.jl, in expression starting on line 94
while loading /home/idunning/pkgtest/.julia/v0.4/FastAnonymous/testusing.jl, in expression starting on line 2

>>> test log
no tests to run
>>> end of log
```

**Comment by timholy** [comment]
Fixed by a2180d1d5c4c119671430475ebfd37a77e97b046
