### ISSUE TITLE
let within (fast) anonymous function do not work

### ISSUE THREAD

**Issue by zenna** [timholy/FastAnonymous.jl#6]
I'm not sure whether you intend to support `let`, but assuming the goal is for fast anonymous should work interchangeably with normal anonymous functions, the following is broken

```julia
@anon ω->begin
  let x = 3
    x
  end
end

julia>x not defined
```

**Comment by timholy** [comment]
I'm too overcommitted to fix this anytime soon, but happy to accept pull requests.

**Comment by malmaud** [comment]
I'm too undercommitted to not fix this.

**Comment by timholy** [comment]
:smile:
