### ISSUE TITLE
Using with `Nullable{Function}`

### ISSUE THREAD

**Issue by dpo** [timholy/FastAnonymous.jl#8]
How can I create a `Nullable{Function}` `anon`-ized anonymous function?
````JULIA
julia> VERSION
v"0.3.6"

julia> using Compat

julia> using FastAnonymous

julia> f = @anon x -> 2*x;

julia> Nullable{Function}(f)
ERROR: `Nullable{Function}` has no method matching Nullable{Function}(::Type{##23149})
````

**Comment by timholy** [comment]
`f` isn't a function. Use `Nullable{typeof(f)}(f)`.

**Comment by dpo** [comment]
Thanks. That's a bit annoying. My use case is to pass an anonymous function to a type constructor that expects a `Nullable{Function}`. What's the best resolution? Change it to `Nullable{Union(Function,DataType)}`?

**Comment by timholy** [comment]
Yes, you have to broaden the type signature of the code that uses this. There's no way (yet) to make it a function and get good performance; this uses a trick of building a special-purpose type.

I did something like this in https://github.com/JuliaLang/julia/pull/10314, perhaps it will help you see how to do it.

**Comment by dpo** [comment]
Many thanks. My initial interest in FastAnonymous was for something like this:

````JULIA
using FastAnonymous
n = 5000;
M = sprand(n, n, .8);
prod = @anon v -> M * v;
# prod = v -> M * v;

v = rand(n);
u = prod(v);
@time u = prod(v);
````
But I'm not seeing any time difference. Is that expected?

**Comment by timholy** [comment]
Yes. All the time spent in your computation is in the matrix multiply. FastAnonymous helps only when the overhead of the function call represents an appreciable fraction of the time. Think about it this way: there's a bit of overhead to "launch" an anonymous function call, but once it gets launched, it's running at full speed.

The other thing to note is that the main point of the package is when you pass a function as an argument to some other function. You'll never notice the overhead of a single call at the REPL.

**Comment by dpo** [comment]
You're right. My test is too simplistic. My application *is* to pass the anonymous function to another function. I'll have to implement the whole thing to find out. Thanks again.

**Comment by timholy** [comment]
I don't think there's anything actionable here, so I'm closing.
